### ISSUE TITLE
Dark/Light mode toggle keeps trying to open previous link

### ISSUE THREAD

**Issue by mahmad97** [WaqasAliAbbasi/WaqasAliAbbasi.github.io#139]
Steps to reproduce:
1. Click the resume dowload button once
2. Now clicking the Dark/Light mode toggle will open whatever previous link user was on

Bug only happens when resume is dowloaded once, goes away on page refresh.

**Comment by WaqasAliAbbasi** [comment]
I think this could be a great feature, keep redirecting people to my resume even if they don't want to look at it? What do you think?

**Comment by mahmad97** [comment]
I believe this effects the usability of the webpage by a bit. Also it reopens your previous link irrespective of what it was.

Imagine the scenario one where a recruiter had just downloaded you resume and was watching something steamy in another tab. Then they closed that other tab. Now if their boss were to borrow their device to look at this website and were to press the theme toggle, it would lead to the steamy website opening.

Thus, this issue is at least a minor inconvenience, and at worst a cause for someone getting fired. Therefore I would recommend fixing this bug.

Edit: By steamy website I am of course referring to [Steam](https://store.steampowered.com/), as browsing a video game distributor would be frowned upon in the office environment.

**Comment by WaqasAliAbbasi** [comment]
That is indeed a very undesirable outcome. I will immediately start working on a on-device facial recognition feature to detect whether the person navigating my website has changed and then conditionally enable/disable this theme-but-actually-back button feature. Thank you for letting me know @mahmad97
